name: Build Develop Registry
# Event triggers
on:
  push:
    branches:
      - "develop"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
          DOCKER_IMAGE_NAME: template
        run: |
          docker buildx create --use
          docker login -u "Joshua Pangaribuan" -p $DOCKER_PAT ghcr.io
          docker buildx build -t ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:develop --push .
